### ISSUE TITLE
Plots in refinement step not popping up

### ISSUE THREAD

**Issue by mdehollander** [minillinim/GroopM#10]
I am running GroopM 0.3.4. At the refinement step the plots are not showing on screen as expected. Instead the menu shows again:
```bash
 Please choose from the following options:
------------------------------------------------------------
 r = plot entire space using bin ids
 p = plot entire space with bins as points
 g = plot entire space for bins within a specific GC range
 u = plot all contigs in untransformed coverage space (first 3 stoits only)
 b = plot one or more bins
 v = plot all contigs in vincinity of bin
 m = merge two or more bins
 s = split a bin into multiple pieces
 c = change colormap
 e = toggle elipses (default = on)
 x = toggle chimeric bins (default = hidden)
 q = quit
------------------------------------------------------------
 What next? (r,p,g,u,b,v,m,s,c,e,x,q) : p
[ 0.63866878  0.50683819  0.44629665  0.33322461  0.35977337  0.6236054
  0.57933657  0.60141476  0.51135851  0.52991453  0.48990579  0.6187313
  0.45233234  0.59586712  0.43921082  0.43425814  0.61175824  0.36654804
  0.50972763  0.66557909  0.63951473  0.63740023  0.59687998  0.46174043
  0.61539913  0.64249888  0.40225891  0.61340206  0.54894589  0.59344578
  0.50626959  0.52279632]

 Please choose from the following options:
------------------------------------------------------------
 r = plot entire space using bin ids
 p = plot entire space with bins as points
```

When I use the `groopm plot` command a file is written to disk, so that works. Any idea how to find out the problem? Any easy way to debug?

Here are my system details
```Tables version: 3.1.1
Location: .virtualenvs/groopm/local/lib/python2.7/site-packages/tables/__init__.pyc
Numpy version: 1.9.2
Location: .virtualenvs/groopm/local/lib/python2.7/site-packages/numpy/__init__.pyc
Scipy version: 0.15.1
Location: .virtualenvs/groopm/local/lib/python2.7/site-packages/scipy/__init__.pyc
MPL version: 1.4.3
Location: .virtualenvs/groopm/local/lib/python2.7/site-packages/matplotlib/__init__.pyc
Linux 3.13.0-48-generic
2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2]
```

Thanks!

**Comment by minillinim** [comment]
Ok, just to confirm
You're able to make images using the groopm plot but in groopm refine the program doesn't make any images pop up on the screen, it just returns to the menu.

It may be the way your system is set up. To test, please go to this url (http://matplotlib.org/examples/color/colormaps_reference.html) and copy the python source into a file on the machine you're running GroopM on, let's call it test.py.

Then at the command prompt type:

$ python test.py

What happens? It should pop four or five windows onto the screen.

**Comment by mdehollander** [comment]
Solved! The problem was that no plot windows are shown within a virtualenv. The solution is to uninstall matplotlib, link the gtk libraries and install again as described here: http://www.stevenmaude.co.uk/2013/09/installing-matplotlib-in-virtualenv.html
